[package]
name = "rk"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["cargo", "string"] }
native-tls = "0.2.12"
openssl = "0.10.64"
tokio = { version = "1.38.0", features = ["full"] }
